export const realMovieCatalogue = [
  {
    legacySlug: "bao-tap-thanh-pho-chim",
    slug: "dune-part-two",
    title: "Dune: Hành Tinh Cát – Phần Hai",
    description: "Paul Atreides hợp lực cùng Chani và người Fremen để trả thù những kẻ đã hủy diệt gia đình mình.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    durationMin: 166,
    ageRating: "T13",
    director: "Denis Villeneuve",
    cast: "Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem",
    releaseDate: new Date("2024-03-01T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 95,
    genres: ["khoa-hoc-vien-tuong", "phieu-luu"],
  },
  {
    legacySlug: "ky-uc-so-0",
    slug: "oppenheimer",
    title: "Oppenheimer",
    description: "Câu chuyện về nhà vật lý J. Robert Oppenheimer và vai trò của ông trong quá trình phát triển bom nguyên tử.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    durationMin: 180,
    ageRating: "T16",
    director: "Christopher Nolan",
    cast: "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.",
    releaseDate: new Date("2023-07-21T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 88,
    genres: ["tam-ly"],
  },
  {
    legacySlug: "tieng-goi-tu-tang-ham",
    slug: "spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
    description: "Peter Parker nhờ Doctor Strange xóa bí mật thân phận, nhưng phép thuật mở ra các mối đe dọa từ đa vũ trụ.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    durationMin: 148,
    ageRating: "T13",
    director: "Jon Watts",
    cast: "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon",
    releaseDate: new Date("2021-12-17T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 90,
    genres: ["hanh-dong", "phieu-luu"],
  },
  {
    legacySlug: "tau-tu-thu-tinh-lan",
    slug: "interstellar",
    title: "Interstellar",
    description: "Trái Đất kiệt quệ, nhóm nhà thám hiểm băng qua hố sâu vũ trụ để tìm hành tinh mới cho nhân loại.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    durationMin: 169,
    ageRating: "T13",
    director: "Christopher Nolan",
    cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
    releaseDate: new Date("2014-11-07T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 91,
    genres: ["khoa-hoc-vien-tuong", "phieu-luu"],
  },
  {
    legacySlug: "biet-doi-cho-hoang",
    slug: "godzilla-x-kong-the-new-empire",
    title: "Godzilla x Kong: Đế Chế Mới",
    description: "Godzilla và Kong đối đầu một mối đe dọa cổ xưa có thể hủy diệt cả Trái Đất.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    durationMin: 115,
    ageRating: "T13",
    director: "Adam Wingard",
    cast: "Rebecca Hall, Brian Tyree Henry, Dan Stevens, Kaylee Hottle",
    releaseDate: new Date("2024-03-29T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 86,
    genres: ["hanh-dong", "khoa-hoc-vien-tuong", "phieu-luu"],
  },
  {
    legacySlug: "vo-cuc-dao",
    slug: "kingdom-of-the-planet-of-the-apes",
    title: "Hành Tinh Khỉ: Vương Quốc Mới",
    description: "Nhiều thế hệ sau Caesar, một chú khỉ trẻ bắt đầu hành trình quyết định tương lai của cả loài khỉ và con người.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    durationMin: 145,
    ageRating: "T13",
    director: "Wes Ball",
    cast: "Owen Teague, Freya Allan, Kevin Durand, Peter Macon",
    releaseDate: new Date("2024-05-10T00:00:00.000Z"),
    status: "NOW_SHOWING",
    popularity: 84,
    genres: ["hanh-dong", "khoa-hoc-vien-tuong", "phieu-luu"],
  },
  {
    legacySlug: "hanh-tinh-thu-chin",
    slug: "kung-fu-panda-4",
    title: "Kung Fu Panda 4",
    description: "Po phải tìm người kế vị mới cho danh hiệu Thần Long Đại Hiệp trước khi một phù thủy nguy hiểm xuất hiện.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    durationMin: 94,
    ageRating: "P",
    director: "Mike Mitchell",
    cast: "Jack Black, Awkwafina, Viola Davis, Dustin Hoffman",
    releaseDate: new Date("2024-03-08T00:00:00.000Z"),
    status: "COMING_SOON",
    popularity: 82,
    genres: ["hoat-hinh", "hai", "phieu-luu"],
  },
  {
    legacySlug: "dam-cuoi-hoang-loan",
    slug: "the-wild-robot",
    title: "Robot Hoang Dã",
    description: "Một robot mắc kẹt trên đảo hoang học cách thích nghi với thiên nhiên và trở thành mẹ của một chú ngỗng con.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    durationMin: 102,
    ageRating: "P",
    director: "Chris Sanders",
    cast: "Lupita Nyong'o, Pedro Pascal, Kit Connor, Bill Nighy",
    releaseDate: new Date("2024-09-27T00:00:00.000Z"),
    status: "COMING_SOON",
    popularity: 89,
    genres: ["hoat-hinh", "phieu-luu"],
  },
  {
    legacySlug: "rung-thieng",
    slug: "wicked",
    title: "Wicked",
    description: "Câu chuyện chưa từng kể về tình bạn giữa Elphaba và Glinda trước khi họ trở thành những phù thủy huyền thoại xứ Oz.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
    durationMin: 160,
    ageRating: "P",
    director: "Jon M. Chu",
    cast: "Cynthia Erivo, Ariana Grande, Jonathan Bailey, Michelle Yeoh",
    releaseDate: new Date("2024-11-22T00:00:00.000Z"),
    status: "COMING_SOON",
    popularity: 87,
    genres: ["tinh-cam", "phieu-luu"],
  },
  {
    legacySlug: "giai-dieu-cuoi-cung",
    slug: "alien-romulus",
    title: "Alien: Romulus",
    description: "Những người định cư trẻ đối mặt với dạng sống đáng sợ nhất vũ trụ khi khám phá một trạm không gian bỏ hoang.",
    posterUrl: "https://image.tmdb.org/t/p/w1280/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    durationMin: 119,
    ageRating: "T18",
    director: "Fede Álvarez",
    cast: "Cailee Spaeny, David Jonsson, Archie Renaux, Isabela Merced",
    releaseDate: new Date("2024-08-16T00:00:00.000Z"),
    status: "COMING_SOON",
    popularity: 85,
    genres: ["kinh-di", "khoa-hoc-vien-tuong"],
  },
] as const;
